import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Wand2, RefreshCw } from "lucide-react";
const ImageGenerationSection = ({ generatedImages, selectedImageIndex, handleImageSelect, handleGenerate, isGenerating, progress, generationError, }) => {
    const handleRetry = async () => {
        await handleGenerate();
    };
    return (_jsxs(Card, { className: "p-6", children: [_jsx("h2", { className: "text-2xl font-semibold mb-4", children: "2. Generate Your Image" }), _jsxs("div", { className: "space-y-4", children: [_jsx("div", { className: "grid grid-cols-3 gap-4", children: [0, 1, 2].map((index) => (_jsxs("div", { className: "flex flex-col items-center", children: [_jsx("div", { className: "w-full h-48 bg-gray-100 rounded-lg mb-2", children: generatedImages[index] && (_jsx("img", { src: generatedImages[index], alt: `Generated option ${index + 1}`, className: "w-full h-full object-cover rounded-lg" })) }), _jsx(Button, { variant: selectedImageIndex === index ? "default" : "outline", className: "w-full", onClick: () => handleImageSelect(index), disabled: !generatedImages[index], children: generatedImages[index] ? "Select" : `Option ${index + 1}` })] }, index))) }), _jsxs("div", { className: "flex gap-2", children: [_jsxs(Button, { onClick: handleGenerate, className: "flex-1 h-12 text-lg", disabled: isGenerating || progress < 100, children: [_jsx(Wand2, { className: "mr-2 h-5 w-5" }), isGenerating ? "Generating..." : "Generate Options"] }), _jsxs(Button, { variant: "secondary", className: "h-12", onClick: handleRetry, children: [_jsx(RefreshCw, { className: "mr-2 h-5 w-5" }), "Retry"] })] }), _jsxs("div", { className: "bg-gray-50 p-4 rounded-lg", children: [_jsx("h3", { className: "font-medium mb-2", children: "AI Generation Tips" }), _jsxs("ul", { className: "text-sm space-y-1", children: [_jsx("li", { children: "\u2022 Be specific about colors and themes" }), _jsx("li", { children: "\u2022 Mention any special occasions" }), _jsx("li", { children: "\u2022 Include preferred art styles" }), _jsx("li", { children: "\u2022 Specify if you want text incorporated" })] })] }), generationError && (_jsx("div", { className: "text-red-500 text-sm", children: generationError }))] })] }));
};
export default ImageGenerationSection;
